---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: openeo-geotrellis
data:
  backendconfig.py: |
    from openeogeotrellis.config import GpsBackendConfig
    from openeogeotrellis.deploy import (
        build_gps_backend_deploy_metadata,
        find_geotrellis_jars,
    )


    capabilities_deploy_metadata = build_gps_backend_deploy_metadata(
        packages=[
            "openeo",
            "openeo_driver",
            "openeo-geopyspark",
            "openeo_udf",
            "geopyspark",
        ],
        jar_paths=find_geotrellis_jars(extra_search_locations=[Path("/opt")]),
    )


    config = GpsBackendConfig(
        id="eoepca-openeo",
        capabilities_title="EOEPCA GeoPySpark Backend",
        capabilities_description="EOEPCA GeoPySpark Backend",
        capabilities_deploy_metadata=capabilities_deploy_metadata,
        enable_basic_auth=True,
        valid_basic_auth=lambda u, p: p == f"{u}123",
    )
